name: code-sniffer
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  phpcs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Composer install
        run: docker-compose run --rm php7.2 composer install
      - name: phpcs
        run: docker-compose run --rm php7.2 ./vendor/bin/phpcs
