name: coverage-report
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  coveralls:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Upload coverage results to Coveralls
        run: |
          docker-compose run \
            -e COVERALLS_REPO_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            --rm php7.2 sh -c '\
              composer install \
              && ./vendor/bin/phpunit --testsuite Unit --coverage-clover .github/logs/clover.xml \
              && ./vendor/bin/php-coveralls --coverage_clover=.github/logs/clover.xml -v \
            '
