name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The bumped up git tag version.'
        required: true
      message:
        description: 'Brief description of new release.'
        required: true
jobs:
  tag-and-publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Remove non production files
        run: |
          rm -rf .docker .github tests .env* .gitignore docker-compose.yml \
            Makefile phpunit.xml
          git add --all && git commit -m 'Remove non production files.'
      - run: |
          git tag \
            --annotate ${{ github.event.inputs.version }} \
            --message ${{ github.event.inputs.description }}
          git push origin ${{ github.event.inputs.version }}

