name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The bumped up git tag version.'
        required: true
      message:
        description: 'Brief description of new release.'
        required: true
jobs:
  integration-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - run: |
          docker-compose run \
            -e ELASTIC_EMAIL_API_KEY=${{ secrets.ELASTIC_EMAIL_API_KEY }} \
            -e TEST_EMAIL_FROM=${{ secrets.TEST_EMAIL_FROM }} \
            -e TEST_EMAIL_TO=${{ secrets.TEST_EMAIL_TO }} \
            -e CI=true \
            --rm php7.2 sh -c '\
              composer install && composer phpunit:integration
            '
  tag-and-publish:
    needs: [integration-test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup GitHub action user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Remove non production files
        run: |
          rm -rf .docker .github tests .env* .gitignore docker-compose.yml \
            Makefile phpunit.xml
          git add --all && git commit -m 'Remove non production files.'
      - run: |
          git tag \
            --annotate "${{ github.event.inputs.version }}" \
            --message "${{ github.event.inputs.message }}"
          git push origin ${{ github.event.inputs.version }}

